// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0HVjIIbqpUSNUebvRUA9I1uXJH02QqkI',
    appId: '1:533758530867:android:39cd2c1de1426f87361a46',
    messagingSenderId: '533758530867',
    projectId: 'agrosmart-e86d3',
    databaseURL:
        'https://agrosmart-e86d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agrosmart-e86d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQuVUi7D3lkchwmuYfxuqFn0BAy3N6wZk',
    appId: '1:533758530867:ios:6940dbea39e563a4361a46',
    messagingSenderId: '533758530867',
    projectId: 'agrosmart-e86d3',
    databaseURL:
        'https://agrosmart-e86d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agrosmart-e86d3.appspot.com',
    iosBundleId: 'com.example.argoSmartV1',
  );
}
